version: "2"

networks:
  default:
    external:
      name: local-network

services:
  mysql:
    image: infomuscle10/mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
    volumes:
      - ./mysql:/var/lib/mysql
  postgres:
    image: infomuscle10/postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/data/pgdata
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  oracle-xe-11g-r2:
    image: infomuscle10/oracle-xe-11g-r2
    container_name: oracle-xe-11g-r2
    ports:
      - "1521:1521"
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - TZ=Asia/Seoul