version: '2'

networks:
  default:
    external:
      name: aws-network

services:
  bortfolio:
    image: infomuscle10/bortfolio
    container_name: bortfolio
    ports:
      - "9000:80"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    volumes:
      - /var/lib/docker/volumes/bortfolio/_data:/tmp
