version: '2'

networks:
  default:
    external:
      name: local-network

services:
  bortfolio:
    image: infomuscle10/bortfolio
    container_name: bortfolio
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    volumes:
      - /var/lib/docker/volumes/bortfolio/_data:/tmp
